// <auto-generated />
using System;
using CyberCafe.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyberCafe.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CyberCafeDbContext))]
    [Migration("20260527040241_AddFoodManagement")]
    partial class AddFoodManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("CyberCafe.Core.Entities.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Specs")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Đồ ăn",
                            Description = "Mì ăn liền vị tôm chua cay",
                            IsAvailable = true,
                            Name = "Mì tôm Hảo Hảo",
                            Price = 15000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Đồ ăn",
                            Description = "Bánh mì nướng phô mai bơ",
                            IsAvailable = true,
                            Name = "Bánh mì phô mai",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Đồ ăn",
                            Description = "Xúc xích chiên giòn",
                            IsAvailable = true,
                            Name = "Xúc xích chiên",
                            Price = 20000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Nước uống",
                            Description = "Nước ngọt Pepsi 330ml",
                            IsAvailable = true,
                            Name = "Pepsi lon",
                            Price = 15000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Nước uống",
                            Description = "Trà sữa trân châu đen 500ml",
                            IsAvailable = true,
                            Name = "Trà sữa trân châu",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Snack",
                            Description = "Snack tôm chua cay 40g",
                            IsAvailable = true,
                            Name = "Snack Oishi tôm chua",
                            Price = 10000m
                        });
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.FoodOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FoodOrders");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.FoodOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("FoodOrderId");

                    b.ToTable("FoodOrderItems");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("WalletId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Standard",
                            PricePerHour = 10000m
                        },
                        new
                        {
                            Id = 2,
                            Name = "VIP",
                            PricePerHour = 25000m
                        });
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.Computer", b =>
                {
                    b.HasOne("CyberCafe.Core.Entities.Zone", "Zone")
                        .WithMany("Computers")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.FoodOrder", b =>
                {
                    b.HasOne("CyberCafe.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.FoodOrderItem", b =>
                {
                    b.HasOne("CyberCafe.Core.Entities.FoodItem", "FoodItem")
                        .WithMany("FoodOrderItems")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CyberCafe.Core.Entities.FoodOrder", "FoodOrder")
                        .WithMany("FoodOrderItems")
                        .HasForeignKey("FoodOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("FoodOrder");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.GameSession", b =>
                {
                    b.HasOne("CyberCafe.Core.Entities.Computer", "Computer")
                        .WithMany("GameSessions")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CyberCafe.Core.Entities.User", "User")
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.Transaction", b =>
                {
                    b.HasOne("CyberCafe.Core.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.Wallet", b =>
                {
                    b.HasOne("CyberCafe.Core.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("CyberCafe.Core.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.Computer", b =>
                {
                    b.Navigation("GameSessions");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.FoodItem", b =>
                {
                    b.Navigation("FoodOrderItems");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.FoodOrder", b =>
                {
                    b.Navigation("FoodOrderItems");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.User", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CyberCafe.Core.Entities.Zone", b =>
                {
                    b.Navigation("Computers");
                });
#pragma warning restore 612, 618
        }
    }
}
